### ISSUE TITLE
When running client, I get the error "Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by shawnshawnshawn01** [kritish-dhaubanjar/collaborative-code-editor-client#1]
To run this client, I ran

```
node js/script.js
```
and tried
```
node script.js
```
inside the js folder.

I end up getting the error:

import Navbar from "./src/components/Navbar.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module

Any idea of what's going on? Am I running this incorrectly or is this a bug?

**Comment by kritish-dhaubanjar** [comment]
@shawnshawnshawn01 
This is not a console application that is intended be run by Browser, and not from node.

Also, this specific issue is regarding the `import` statement. Node js doesn't support ES6 import directly. If we try to use import for importing modules directly in node js it will throw out the error.
